### ISSUE TITLE
Tietyöilmoituspalvelu lähettää T-LOIK-järjestelmään tallennetut ilmoitukset hyväksyttäväksi.

### ISSUE THREAD

**Issue by jarmosantti-atostek** [tmfg/tietyoilmoituspalvelu-backend#5]
**Kuvaus:** 
Kun käyttäjä on lähettänyt/tallentanut tietyöilmoituksen tai siihen liittyvän osatyökohdeilmoituksen, tieto tästä välitetään T-LOIKiin päivystäjän käsittelyä varten. Tietyöilmoituspalvelu laittaa viestin SQS-viestiväylään, jota kautta se päätyy T-LOIKiin.

**Hyväksymiskriteerit:** 
- Ilmoitus lähetetään täytön jälkeen T-LOIKiin

**Miten (UX):**

**Käyttöliittymäsuunnitelma:**

**Tekninen toteutus ja rajoitukset:**

**Hyväksyntätestit:**

**Comment by MikkoKarhunsuo** [comment]
Toteutettu.
